// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRMtmllj0b_GAitCUQirAoMGXr9QzJZ0',
    appId: '1:578147249233:android:f7e18e469c061cc6f71c70',
    messagingSenderId: '578147249233',
    projectId: 'tradewatchnew',
    storageBucket: 'tradewatchnew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-AbaE3cNi6067q4N3iBnt2bS5RuOW6GM',
    appId: '1:578147249233:ios:6fd3e0513b8877a7f71c70',
    messagingSenderId: '578147249233',
    projectId: 'tradewatchnew',
    storageBucket: 'tradewatchnew.appspot.com',
    androidClientId: '578147249233-0quj9u39lmofmds99mak9m2dbriunf9o.apps.googleusercontent.com',
    iosClientId: '578147249233-431nqa1b1mqndgr2saci6433clk43dcr.apps.googleusercontent.com',
    iosBundleId: 'com.tradewatch.tradewatch',
  );
}
